version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: myapp_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydatalecturer
      MYSQL_USER: root
      MYSQL_PASSWORD: rootroot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro

  backend:
    build: ./backend
    container_name: myapp_backend
    restart: unless-stopped
    
    environment:
      DB_HOST: mysql
      DB_NAME: mydatalecturer
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql_data:
